FORMAT: 1A
HOST: http://localhost:8111

# Business Card API Gateway

Verwaltung der Business Card und Kontakte

## Log In [/login]

### Log In [POST]

Authentifiziert den User gegenüber dem System

+ Request (application/json)

        [
            {
                "user":"JohnDoe",
                "password":"password123"
            }
        ]

+ Response 200 (application/json)

    + Body

            {
                "token": "xxxxxxx.yyyyyyy.zzzzzzz"
            }

## Sign In [/register]

### Sign In [POST]

Erstellt einen neuen Account

+ Request (application/json)

        [
            {
                "user":"JohnDoe",
                "e-mail":"john@doe.com",
                "password":"password123"
            }
        ]

+ Response 201 (application/json)

    + Body

            {
                "token": "xxxxxxx.yyyyyyy.zzzzzzz"
            }

## Confirm [/register/{confirmationID}]

### Confirmation [GET]

Validiert die E-Mail adresse und aktiviert den Account

+ Response 200

## Account [/account/{confirmationID}]

### Update Password/Email [PUT]

Updated das Password und/oder Email

+ Request (application/json)

        [
            {
                "name":"JohnDoe",
                "e-mail":"john@doe.com",
                "password":"password123"
            }
        ]
        
+ Response 201

## Business Cards [/businesscard]

### Create Business Card [POST]

Erstellt eine neue Business Card

+ Request (application/json)

        [
            {
                "title": ["PhD", "Prof"],
                "information": 
                    {
                        "firstname":"John",
                        "lastname":"Doe",
                        "additionalField1":"additionalField1",
                        "additionalField2":"additionalField1"
                    },
                "contact":
                    {
                        "e-mail":"john@doe.com",
                        "phone":"555-555-555",
                        "additionalField1":"additionalField1",
                        "additionalField2":"additionalField1"
                    },
                "detail":
                    {
                        "business":"CEO",
                        "compoany":"Microsoft"
                    }
            }
        ]

+ Response 201 (application/json)

    + Body

            {
                "title": ["PhD", "Prof"],
                "information": 
                    {
                        "firstname":"Joe",
                        "lastname":"Doe",
                        "additionalField1":"additionalField1",
                        "additionalField2":"additionalField1"
                    },
                "contact":
                    {
                        "e-mail":"joe@doe.com",
                        "phone":"555-555-555",
                        "additionalField1":"additionalField1",
                        "additionalField2":"additionalField1"
                    },
                "detail":
                    {
                        "business":"CTO",
                        "compoany":"Microsoft"
                    }
            }


## Business Card [/businesscard/{shareId}]

### Get Own Business Card  [GET]

Lädt die eigene Business Card

+ Response 200 (application/json)

        [
            {
                "title": ["PhD", "Prof"],
                "information": 
                    {
                        "firstname":"John",
                        "lastname":"Doe",
                        "additionalField1":"additionalField1",
                        "additionalField2":"additionalField1"
                    },
                "contact":
                    {
                        "e-mail":"john@doe.com",
                        "phone":"555-555-555",
                        "additionalField1":"additionalField1",
                        "additionalField2":"additionalField1"
                    },
                "detail":
                    {
                        "business":"CEO",
                        "compoany":"Microsoft"
                    }
            }
        ]

### Update Business Card [PUT]

Updated die Business Card für die neuen Felder.
<br/>Wenn man für das Feld <b>titel</b> ein Element hinzufügt, das schon existiert, wird es gelöscht.
<br/>Setzt man in einer Map ein Feld auf null setzt, wird es gelöscht.

+ Request (application/json)

        [
            {
                "title": ["PhD"],
                "information": 
                    {
                        "firstname":"Joe",
                        "additionalField1": "null"
                    },
                "contact":
                    {
                        "e-mail":"joe@doe.com",
                    },
                "detail":
                    {
                        "business":"CTO",
                    }
            }
        ]

+ Response 200 (application/json)

    + Body

            {
                "title": ["Prof"],
                "information": 
                    {
                        "firstname":"Joe",
                        "lastname":"Doe",
                        "additionalField2":"additionalField1"
                    },
                "contact":
                    {
                        "e-mail":"joe@doe.com",
                        "phone":"555-555-555",
                        "additionalField1":"additionalField1",
                        "additionalField2":"additionalField1"
                    },
                "detail":
                    {
                        "business":"CTO",
                        "compoany":"Microsoft"
                    }
            }
      
### Delete Business Card [DELETE]

Löschen oder Deaktivieren eigener Business Card
<br/>Mit dem Feld <b>action</b> kann man bestimmen ob die Business Card deaktiviert oder gelöscht werden soll

+ Request (application/json)

        [
            {
                "action": "deactivate|delete"
            }
        ]

+ Response 200 

## Contacts [/businesscard/{shareId}/contacts/]

### Get Contacts  [GET]

Lädt die eigene Business Card

+ Response 200 (application/json)

        {
                information: 
                    {
                        "title": ["PhD"]
                        "firstname":"Jane",
                        "lastname":"Doe",
                        "additionalField1":"additionalField1",
                    },
                "contact":
                    {
                        "e-mail":"jane@doe.com",
                        "phone":"555-555-555",
                        "additionalField1":"additionalField1",
                    },
                "detail":
                    {
                        "business":"Housewife"
                    }
            },
            {
                information: 
                    {
                        "firstname":"Will",
                        "lastname":"Smith"
                    },
                "contact":
                    {
                        "e-mail":"will@smith.com",
                        "phone":"555-555-555"
                    },
                "detail":
                    {
                        "business":"Actor",
                    }
            }

### Add Contact  [POST]

Fügt einen Kontakt hinzu

+ Request (application/json)

        [
            {
                "shareLink":"a6df876da5" 
            }
        ]

+ Response 201 

## Contact [/businesscard/{shareId}/contact/{contactshareId}]

### Get Contact  [GET]

Lädt einen speziellen Kontakt

+ Response 200 (application/json)

            {
                information: 
                    {
                        "title": ["PhD"]
                        "firstname":"Jane",
                        "lastname":"Doe",
                        "additionalField1":"additionalField1",
                    },
                "contact":
                    {
                        "e-mail":"jane@doe.com",
                        "phone":"555-555-555",
                        "additionalField1":"additionalField1",
                    },
                "detail":
                    {
                        "business":"Housewife"
                    }
            }

### Delete Contact  [DELETE]

Löscht den Kontakt aus der Liste der Kontakte

+ Response 200

## Share [/businesscard/{shareId}/share]

### Get Share Link [GET]

Erstellt oder Lädt einen Share Link zur eigenen Business Card

+ Response 200 (application/json)

            {
                "shareLink":"a987df6"
            }